# ("HELLO WORLD")
#  COMMENTS (CTRL+/)
#  MULTILINE COMMENT ("""" """)
#  SCAPE SEQUNCE (\N)

# ARITHMETIC OPERATORS

# (+) TO ADD THE VALUES
# (-) TO SUBTRATCT THE VALUES
# (%) TO GIVE THE REMINDER 
# (/) FOR DEVSION
# (//)
# (*) TO MULTIPLY THE VALUES
# (**)

# CONDITIONAL OPERATORS

# > (GREATER)
# < (LESS THEN)
# <= (LESS THEN EQUALTO)
# >= (GREATER THEN EQUAL TO)
# != (NOT EQUAL TO)
# == (EQUAL TO)


# name = "tanzeem sheikh"
# print(name.split())

# name = input("what is your name")
# a = name.split()
# print(a)

